/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.erhannis.ivorydamagescripts;

/**
 *
 * @author erhannis
 */
public class MainFrame extends javax.swing.JFrame {
    public static final Attack PERFORMANCE = new Attack(new Roll(3), new Roll(3));
    public static final Attack FLANKING = new Attack(new Roll(2), Roll.ndn(8, new MinDie(4, 2), 0));
    public static final Attack HOLY_DAMAGE = new Attack(new Roll(0), new Roll(0, Die.D6, Die.D6));

    private static javax.swing.JTextPane logPanel;
    public static void log(String s) {
        logPanel.setText(logPanel.getText()+s);
    }
    public static void logln(String s) {
        logPanel.setText(logPanel.getText()+s+"\n");
    }
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        logPanel = this.jTextPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnBite = new javax.swing.JButton();
        cbFlanking = new javax.swing.JCheckBox();
        cbPerformance = new javax.swing.JCheckBox();
        cbHolyDamage = new javax.swing.JCheckBox();
        btnFullAttack = new javax.swing.JButton();
        btnFlyingFullAttack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnBite.setText("Bite");
        btnBite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiteActionPerformed(evt);
            }
        });

        cbFlanking.setSelected(true);
        cbFlanking.setText("Flanking");

        cbPerformance.setSelected(true);
        cbPerformance.setText("Performance");

        cbHolyDamage.setSelected(true);
        cbHolyDamage.setText("Holy damage");

        btnFullAttack.setText("Full attack");
        btnFullAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullAttackActionPerformed(evt);
            }
        });

        btnFlyingFullAttack.setText("Flying full attack");
        btnFlyingFullAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlyingFullAttackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFlanking)
                    .addComponent(cbPerformance)
                    .addComponent(cbHolyDamage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFullAttack, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFlyingFullAttack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPerformance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFlanking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHolyDamage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFullAttack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFlyingFullAttack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBite)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jScrollPane1.setViewportView(jTextPane1);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public CompoundAttack modify(CompoundAttack atk) {
        if (cbPerformance.isSelected()) {
            atk = atk.plus(PERFORMANCE);
        }
        if (cbHolyDamage.isSelected()) {
            atk = atk.plus(HOLY_DAMAGE);
        }
        if (cbFlanking.isSelected()) {
            atk = atk.plus(FLANKING);
        }
        return atk;
    }
    
    public void doBite() {
        CompoundAttack ca = new CompoundAttack(new Roll(16, Die.D20), Roll.ndn(2, Die.D8, 8));
        ca = modify(ca);
        System.out.println("Bite toHit:");
        int t = ca.rollToHit();
        System.out.println(" total " + t);
        System.out.println("Bite toDamage:");
        t = ca.rollToDamage();
        System.out.println(" total " + t);
        System.out.println("");
    }

    public void doClaw() {
        CompoundAttack ca = new CompoundAttack(new Roll(14, Die.D20), Roll.ndn(1, Die.D8, 3));
        ca = modify(ca);
        System.out.println("Claw toHit:");
        int t = ca.rollToHit();
        System.out.println(" total " + t);
        System.out.println("Claw toDamage:");
        t = ca.rollToDamage();
        System.out.println(" total " + t);
        System.out.println("");
    }

    public void doWing() {
        CompoundAttack ca = new CompoundAttack(new Roll(14, Die.D20), Roll.ndn(1, Die.D8, 3));
        ca = modify(ca);
        System.out.println("Wing toHit:");
        int t = ca.rollToHit();
        System.out.println(" total " + t);
        System.out.println("Wing toDamage:");
        t = ca.rollToDamage();
        System.out.println(" total " + t);
        System.out.println("");
    }
    
    public void doTail() {
        CompoundAttack ca = new CompoundAttack(new Roll(14, Die.D20), Roll.ndn(2, Die.D6, 8));
        ca = modify(ca);
        System.out.println("Tail toHit:");
        int t = ca.rollToHit();
        System.out.println(" total " + t);
        System.out.println("Tail toDamage:");
        t = ca.rollToDamage();
        System.out.println(" total " + t);
        System.out.println("");
    }

    private void btnBiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiteActionPerformed
        doBite();
        System.out.println("----");
    }//GEN-LAST:event_btnBiteActionPerformed

    private void btnFullAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullAttackActionPerformed
        doBite();
        doClaw();
        doClaw();
        doWing();
        doWing();
        doTail();
        System.out.println("----");
    }//GEN-LAST:event_btnFullAttackActionPerformed

    private void btnFlyingFullAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlyingFullAttackActionPerformed
        doBite();
        doClaw();
        doClaw();
        doTail();
        System.out.println("----");
    }//GEN-LAST:event_btnFlyingFullAttackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBite;
    private javax.swing.JButton btnFlyingFullAttack;
    private javax.swing.JButton btnFullAttack;
    private javax.swing.JCheckBox cbFlanking;
    private javax.swing.JCheckBox cbHolyDamage;
    private javax.swing.JCheckBox cbPerformance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
